from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PYTHON_DOCS_DIR = RAW_DATA_DIR / "python_docs"
TEXTBOOKS_DIR = RAW_DATA_DIR / "textbooks"
STACKOVERFLOW_DIR = RAW_DATA_DIR / "stackoverflow"
JUPYTER_DIR = RAW_DATA_DIR / "jupyter"
CODESEARCHNET_DIR = RAW_DATA_DIR / "codesearchnet"
THE_STACK_DIR = RAW_DATA_DIR / "the_stack"

FILTERED_DATA_DIR = DATA_DIR / "filtered"
STAGE1_DIR = FILTERED_DATA_DIR / "stage1"
STAGE2_DIR = FILTERED_DATA_DIR / "stage2"
STAGE3_DIR = FILTERED_DATA_DIR / "stage3"
FINAL_DATA_DIR = DATA_DIR / "final"
FINAL_CORPUS_PATH = FINAL_DATA_DIR / "corpus.jsonl"

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
VALIDATORS_DIR = SCRIPTS_DIR / "validators"
SCRAPERS_DIR = SCRIPTS_DIR / "scrapers"
PROCESSORS_DIR = SCRIPTS_DIR / "processors"
LOGS_DIR = PROJECT_ROOT / "logs"
LOG_FILE = LOGS_DIR / "pipeline.log"

MIN_TOKEN_LENGTH = 50
MAX_TOKEN_LENGTH = 2048
MIN_COMMENT_RATIO = 0.1
PEP8_MAX_VIOLATIONS = 5
DEDUP_SIMILARITY_THRESHOLD = 0.85
