"""Quality reporting infrastructure — Pythia-160M.

Produces per-source quality summaries from evaluation results generated by
the quality-gate layer. Does not modify raw records or acquisition data.

Reports identify:
  - source, source version, dataset version where available
  - experiment ID, validator version, timestamp

The names "final" or "final corpus" are NOT used unless the dataset has
actually passed final-corpus admission.

Import: ``json`` for ``write_report``.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from scripts.quality_gate import evaluate_record


def _now_iso() -> str:
    """Return the current UTC time in ISO format."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _safe_int(val: any, default: int = 0) -> int:
    """Coerce *val* to int; return *default* if impossible."""
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def _safe_float(val: any, default: float = 0.0) -> float:
    """Coerce *val* to float; return *default* if impossible."""
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


class QualitySummary:
    """Accumulate per-source quality metrics and emit a summary report."""

    def __init__(
        self,
        source: str,
        source_version: str = "unknown",
        dataset_version: Optional[str] = None,
        experiment_id: Optional[str] = None,
        validator_version: str = "scripts.validators.ast_validator",
    ) -> None:
        self.source = source
        self.source_version = source_version
        self.dataset_version = dataset_version
        self.experiment_id = experiment_id
        self.validator_version = validator_version

        # Accumulators
        self.records_examined: int = 0
        self.records_accepted: int = 0
        self.records_rejected: int = 0
        self.ast_valid_count: int = 0
        self.ast_invalid_count: int = 0
        self.total_pep8_violations: int = 0
        self.total_comment_ratio: float = 0.0
        self.total_docstring_ratio: float = 0.0
        self.total_token_count: int = 0
        self.generated_or_vendor_count: int = 0
        self.license_status_counts: Dict[str, int] = {}
        self.rejection_reasons: Dict[str, int] = {}
        self.token_count_status_counts: Dict[str, int] = {}
        self.provenance_complete_count: int = 0
        self.provenance_incomplete_count: int = 0

    def add_record(self, record: dict[str, any], evaluation: dict[str, any]) -> None:
        """Add one record's evaluation to the accumulators."""

        self.records_examined += 1

        # Accept/reject
        if evaluation.get("quality_gate_status") == "ACCEPTED":
            self.records_accepted += 1
        else:
            self.records_rejected += 1

        # AST
        if evaluation.get("ast_valid"):
            self.ast_valid_count += 1
        else:
            self.ast_invalid_count += 1

        # PEP8
        self.total_pep8_violations += _safe_int(evaluation.get("pep8_violations"))

        # Comment / docstring ratios
        self.total_comment_ratio += _safe_float(evaluation.get("comment_ratio", 0))
        self.total_docstring_ratio += _safe_float(evaluation.get("docstring_ratio", 0))

        # Token count
        tc = _safe_int(evaluation.get("token_count", 0))
        self.total_token_count += tc

        # Generated / vendor
        if evaluation.get("generated_or_vendor"):
            self.generated_or_vendor_count += 1

        # License status
        lic = evaluation.get("license_status")
        if lic:
            self.license_status_counts[lic] = self.license_status_counts.get(lic, 0) + 1

        # Token count status
        tcs = evaluation.get("token_count_status")
        if tcs:
            self.token_count_status_counts[tcs] = self.token_count_status_counts.get(tcs, 0) + 1

        # Provenance completeness (basic check: presence of key fields)
        has_provenance = all(
            evaluation.get(k) is not None
            for k in ("source", "record_id", "content_hash", "acquisition_date")
        )
        if has_provenance:
            self.provenance_complete_count += 1
        else:
            self.provenance_incomplete_count += 1

        # Rejection reasons accumulation
        for reason in evaluation.get("rejection_reasons", []):
            self.rejection_reasons[reason] = self.rejection_reasons.get(reason, 0) + 1

    def summary(self) -> dict[str, any]:
        """Return the accumulated quality summary as a dict."""
        n = self.records_examined or 1  # avoid div‑by‑zero
        return {
            "source": self.source,
            "source_version": self.source_version,
            "dataset_version": self.dataset_version,
            "experiment_id": self.experiment_id,
            "validator_version": self.validator_version,
            "timestamp": _now_iso(),
            "records_examined": self.records_examined,
            "records_accepted": self.records_accepted,
            "records_rejected": self.records_rejected,
            "acceptance_rate": self.records_accepted / n,
            "ast_valid_count": self.ast_valid_count,
            "ast_invalid_count": self.ast_invalid_count,
            "pep8_violations": {
                "total": self.total_pep8_violations,
                "average_per_record": round(self.total_pep8_violations / n, 2),
            },
            "comment_ratio": {
                "total": round(self.total_comment_ratio, 4),
                "average_per_record": round(self.total_comment_ratio / n, 4),
            },
            "docstring_ratio": {
                "total": round(self.total_docstring_ratio, 4),
                "average_per_record": round(self.total_docstring_ratio / n, 4),
            },
            "token_count": {
                "total": self.total_token_count,
                "average_per_record": round(self.total_token_count / n, 2),
            },
            "generated_or_vendor_count": self.generated_or_vendor_count,
            "license_status_counts": self.license_status_counts,
            "token_count_status_counts": self.token_count_status_counts,
            "provenance_complete_count": self.provenance_complete_count,
            "provenance_incomplete_count": self.provenance_incomplete_count,
            "rejection_reasons": self.rejection_reasons,
        }

    def write_report(self, path: Path | str) -> None:
        """Write the summary dict as JSON to *path*."""
        report_path = Path(path)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(self.summary(), f, indent=2, sort_keys=True)


def aggregate_summaries(
    summaries: List[QualitySummary],
) -> dict[str, any]:
    """Aggregate multiple QualitySummary instances into one report.

    Useful when combining results across sources or experiments.
    """
    if not summaries:
        return {}

    # Start from the first summary and add the rest
    aggregated = summaries[0]
    for s in summaries[1:]:
        # Simple numeric addition for accumulators
        aggregated.records_examined += s.records_examined
        aggregated.records_accepted += s.records_accepted
        aggregated.records_rejected += s.records_rejected
        aggregated.ast_valid_count += s.ast_valid_count
        aggregated.ast_invalid_count += s.ast_invalid_count
        aggregated.total_pep8_violations += s.total_pep8_violations
        aggregated.total_comment_ratio += s.total_comment_ratio
        aggregated.total_docstring_ratio += s.total_docstring_ratio
        aggregated.total_token_count += s.total_token_count
        aggregated.generated_or_vendor_count += s.generated_or_vendor_count

        # Merge license_status_counts
        for lic, count in s.license_status_counts.items():
            aggregated.license_status_counts[lic] = (
                aggregated.license_status_counts.get(lic, 0) + count
            )

        # Merge token_count_status_counts
        for tcs, count in s.token_count_status_counts.items():
            aggregated.token_count_status_counts[tcs] = (
                aggregated.token_count_status_counts.get(tcs, 0) + count
            )

        # Merge rejection_reasons
        for reason, count in s.rejection_reasons.items():
            aggregated.rejection_reasons[reason] = (
                aggregated.rejection_reasons.get(reason, 0) + count
            )

        # Weighted averages for comment/docstring ratios
        aggregated.total_comment_ratio += s.total_comment_ratio
        aggregated.total_docstring_ratio += s.total_docstring_ratio

    return aggregated.summary()