"""Quality-gate infrastructure — Pythia-160M.

Reusable evaluation layer around existing validators (AST, PEP8, token count,
generated/vendor detection). Produces structured, deterministic metadata.

DO NOT invent arbitrary new thresholds. Reuse configured constants from config.py.

Key philosophical distinctions:
  - AST validity   != semantic correctness
  - PEP8 compliance != code correctness
  - token count     != code quality

All evaluation is deterministic and non-destructive. Raw records are never
modified. Evaluation results are standalone metadata — they do not alter the
records they describe.
"""

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

import pycodestyle  # noqa: F401

# Ensure config constants are available
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from config import (
    MIN_TOKEN_LENGTH,
    MAX_TOKEN_LENGTH,
    MIN_COMMENT_RATIO,
    PEP8_MAX_VIOLATIONS,
    DEDUP_SIMILARITY_THRESHOLD,
)
from scripts.validators.ast_validator import validate_python


def _run_pep8_check(code: str) -> int:
    """Run PEP8 check on *code* and return the violation count.

    Uses pycodestyle.StyleGuide with a temporary file so that theChecker
    API (which expects a filename) works correctly.  The result is
    deterministic for the same input code.
    """
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(code)
        tmp_path = tmp.name
    try:
        style = pycodestyle.StyleGuide(files=[tmp_path], quiet=True)
        report = style.check_files()
        return report  # 0 = clean, 1+ = violations
    finally:
        os.unlink(tmp_path)


def _run_ast_validation(code: str) -> dict:
    """Run the AST validator and return its result dict."""
    return validate_python(code)


def evaluate_quality(code: str) -> dict[str, any]:
    """Evaluate Python code quality and return structured metadata.

    This is a deterministic, non-destructive evaluation. It does not modify
    the input code or any records.

    The evaluation covers:
    - AST validity (syntax structure only, NOT semantic correctness)
    - PEP8 violation count (NOT equivalent to code correctness)
    - Comment / docstring ratios
    - Generated / vendor code flags
    - Provisional token count (char_count // 4)
    - Quality gate status with rejection reasons

    Args:
        code: Python source code string to evaluate.

    Returns:
        dict with keys:
        - ast_valid: bool — whether the code passes AST validation
        - pep8_violations: int — number of PEP8 violations observed
        - comment_ratio: float — ratio of comment lines to total lines
        - docstring_ratio: float — ratio of docstring-bearing lines
        - generated_or_vendor: bool — whether code appears generated/vendor
        - token_count: int — provisional token count (char_count // 4)
        - quality_gate_status: str — "ACCEPTED" or "REJECTED"
        - rejection_reasons: list[str] — why code was rejected, if applicable
    """
    # --- AST validation ---
    ast_result = _run_ast_validation(code)
    ast_valid = ast_result.is_valid

    # --- PEP8 violations ---
    pep8_violations = _run_pep8_check(code)
    # _run_pep8_check returns a BaseReport; extract the total error count
    if hasattr(pep8_violations, "get_count"):
        pep8_violations = pep8_violations.get_count("total_errors")
    else:
        pep8_violations = int(pep8_violations)

    # --- Comment / docstring ratio ---
    lines = [l for l in code.split("\n") if l.strip() is not None]
    total_lines = len(lines)
    if total_lines == 0:
        comment_ratio = 0.0
        docstring_ratio = 0.0
    else:
        # Comment lines: lines whose first non-whitespace char is "#"
        comment_lines = sum(
            1 for l in lines if l.strip().startswith("#")
        )
        comment_ratio = comment_lines / total_lines

        # Docstring lines: lines containing '"""'
        docstring_lines = sum(1 for l in lines if '"""' in l)
        docstring_ratio = docstring_lines / total_lines

    # --- Generated / vendor detection ---
    code_lower = code.lower()
    generated_markers = [
        "do not edit", "generated", "autogenerated", "third_party",
    ]
    generated_or_vendor = any(marker in code_lower for marker in generated_markers)

    # --- Provisional token count ---
    # 1 token ≈ 4 characters ≈ 2 words (provisional method, no PYTHIA-TOK yet)
    char_count = len(code)
    token_count = max(1, char_count // 4)

    # --- Quality gate decision ---
    rejection_reasons: list[str] = []

    # Check minimum token length
    if token_count < MIN_TOKEN_LENGTH:
        rejection_reasons.append(
            f"token_count {token_count} < MIN_TOKEN_LENGTH {MIN_TOKEN_LENGTH}"
        )

    # Check maximum token length
    if token_count > MAX_TOKEN_LENGTH:
        rejection_reasons.append(
            f"token_count {token_count} > MAX_TOKEN_LENGTH {MAX_TOKEN_LENGTH}"
        )

    # Check comment ratio
    if MIN_COMMENT_RATIO > 0 and comment_ratio < MIN_COMMENT_RATIO:
        rejection_reasons.append(
            f"comment_ratio {comment_ratio:.2f} < MIN_COMMENT_RATIO {MIN_COMMENT_RATIO}"
        )

    # Check PEP8 violations
    if pep8_violations > PEP8_MAX_VIOLATIONS:
        rejection_reasons.append(
            f"pep8_violations {pep8_violations} > PEP8_MAX_VIOLATIONS {PEP8_MAX_VIOLATIONS}"
        )

    # Check AST validity — but document that this ≠ semantic correctness
    if not ast_valid:
        rejection_reasons.append("ast_valid=False (syntax structure issue)")

    # Quality gate status
    if rejection_reasons:
        quality_gate_status = "REJECTED"
    else:
        quality_gate_status = "ACCEPTED"

    return {
        "ast_valid": ast_valid,
        "pep8_violations": pep8_violations,
        "comment_ratio": round(comment_ratio, 4),
        "docstring_ratio": round(docstring_ratio, 4),
        "generated_or_vendor": generated_or_vendor,
        "token_count": token_count,
        "quality_gate_status": quality_gate_status,
        "rejection_reasons": rejection_reasons,
    }


def evaluate_record(record: dict[str, any]) -> dict[str, any]:
    """Evaluate quality of a record from the canonical corpus.

    Accepts a record dict that must contain a 'code' key with Python source.

    Returns the same structured metadata as evaluate_quality(), with the
    record's source provenance included in the output for traceability.

    Args:
        record: dict with at minimum a 'code' key containing Python source.

    Returns:
        Structured quality metadata dict with source/provenance fields.
    """
    code = record.get("code", "")
    if not code:
        return {
            "ast_valid": False,
            "pep8_violations": 0,
            "comment_ratio": 0.0,
            "docstring_ratio": 0.0,
            "generated_or_vendor": False,
            "token_count": 0,
            "quality_gate_status": "REJECTED",
            "rejection_reasons": ["empty code field"],
            "source": record.get("source", "unknown"),
            "record_id": record.get("record_id", "unknown"),
        }

    result = evaluate_quality(code)
    result["source"] = record.get("source", "unknown")
    result["record_id"] = record.get("record_id", "unknown")
    result["source_version"] = record.get("source_version", "unknown")
    return result